/**
 * Default settings for the cgateweb bridge.
 * These can be overridden by user settings in settings.js
 */
const defaultSettings = {
    mqtt: 'localhost:1883',
    cbusip: 'your-cgate-ip',
    cbusname: 'CLIPSAL',
    cbuscommandport: 20023,
    cbuseventport: 20025,
    cgateusername: null,
    cgatepassword: null,
    retainreads: false,
    logging: true,
    log_level: 'info',
    messageinterval: 200,
    commandMinIntervalMs: 10,
    maxQueueSize: 1000,
    getallnetapp: null,
    getallonstart: false,
    getallperiod: null,
    getall_app_periods: {},
    mqttusername: null,
    mqttpassword: null,
    mqttUseTls: false,
    mqttCaFile: null,
    mqttCertFile: null,
    mqttKeyFile: null,
    mqttRejectUnauthorized: true,
    reconnectinitialdelay: 1000,
    reconnectmaxdelay: 60000,
    connectionPoolSize: 3,
    healthCheckInterval: 30000,
    keepAliveInterval: 60000,
    eventConnectionKeepAliveInterval: 60000,
    connectionTimeout: 5000,
    maxRetries: 3,
    eventPublishDedupWindowMs: 0,
    eventPublishDedupMaxEntries: 5000,
    topicCacheMaxEntries: 5000,
    eventPublishCoalesce: false,
    auto_discover_networks: true,
    ha_discovery_enabled: false,
    ha_discovery_prefix: 'homeassistant',
    ha_discovery_networks: [],
    ha_discovery_cover_app_id: null,
    cover_ramp_duration_ms: 5000,
    ha_discovery_cover_tilt_app_id: null,
    ha_discovery_switch_app_id: null,
    ha_discovery_relay_app_id: null,
    ha_discovery_pir_app_id: null,
    ha_discovery_trigger_app_id: null,
    ha_discovery_scene_enabled: true,
    ha_discovery_hvac_app_id: null,
    ha_hvac_temperature_unit: 'C',
    ha_bridge_diagnostics_enabled: true,
    ha_bridge_diagnostics_interval_sec: 60,
    stale_device_detection_enabled: true,
    stale_device_threshold_hours: 24,
    stale_device_check_interval_sec: 3600,
    cbus_label_file: null,
    web_port: 8080,
    web_bind_host: '127.0.0.1',
    web_api_key: null,
    web_allow_unauthenticated_mutations: false,
    web_allowed_origins: null,
    web_mutation_rate_limit_per_minute: 120,
    relativeLevelTimeoutMs: 5000,
    // HA Discovery TreeXML retry tuning. C-Gate accepts connections on the
    // command port before its networks are loaded, so an initial TREEXML can
    // return 401 "Network not found". These control the retry budget.
    haDiscoveryMaxTreeRetryAttempts: 8,
    haDiscoveryTreeRetryInitialDelayMs: 2000,
    haDiscoveryTreeRetryMaxDelayMs: 60000,
    haDiscoveryTreeRequestTimeoutMs: 8000,
    // Maximum size (bytes) for POST/PUT/PATCH request bodies on the web UI's
    // label-editing API. Default 10MB covers typical .cbz uploads.
    webMaxBodySizeBytes: 10 * 1024 * 1024
};

module.exports = { defaultSettings };
